// Everyday English country names for the student "Country" field. The
// official ISO name and common alternatives are search aliases, so tutors
// find "United States" by typing "USA" or "Iran" by typing "Persia".
// Based on ISO 3166 (plus Kosovo); edit by hand.
export const COUNTRIES = [
  ["Afghanistan"],
  ["Åland Islands"],
  ["Albania"],
  ["Algeria"],
  ["American Samoa"],
  ["Andorra"],
  ["Angola"],
  ["Anguilla"],
  ["Antarctica"],
  ["Antigua and Barbuda"],
  ["Argentina"],
  ["Armenia"],
  ["Aruba"],
  ["Australia"],
  ["Austria", ["Österreich"]],
  ["Azerbaijan"],
  ["Bahamas"],
  ["Bahrain"],
  ["Bangladesh"],
  ["Barbados"],
  ["Belarus"],
  ["Belgium"],
  ["Belize"],
  ["Benin"],
  ["Bermuda"],
  ["Bhutan"],
  ["Bolivia", ["Bolivia (Plurinational State of)"]],
  ["Bosnia and Herzegovina"],
  ["Botswana"],
  ["Bouvet Island"],
  ["Brazil"],
  ["British Indian Ocean Territory"],
  ["British Virgin Islands", ["Virgin Islands (British)"]],
  ["Brunei", ["Brunei Darussalam"]],
  ["Bulgaria"],
  ["Burkina Faso"],
  ["Burundi"],
  ["Cambodia"],
  ["Cameroon"],
  ["Canada"],
  ["Cape Verde", ["Cabo Verde"]],
  ["Caribbean Netherlands", ["Bonaire, Sint Eustatius and Saba"]],
  ["Cayman Islands"],
  ["Central African Republic"],
  ["Chad"],
  ["Chile"],
  ["China"],
  ["Christmas Island"],
  ["Cocos (Keeling) Islands"],
  ["Colombia"],
  ["Comoros"],
  ["Cook Islands"],
  ["Costa Rica"],
  ["Côte d'Ivoire", ["Ivory Coast"]],
  ["Croatia"],
  ["Cuba"],
  ["Curaçao"],
  ["Cyprus"],
  ["Czechia", ["Czech Republic"]],
  ["Denmark"],
  ["Djibouti"],
  ["Dominica"],
  ["Dominican Republic"],
  ["DR Congo", ["Congo (the Democratic Republic of the)","Congo","Kinshasa"]],
  ["Ecuador"],
  ["Egypt"],
  ["El Salvador"],
  ["Equatorial Guinea"],
  ["Eritrea"],
  ["Estonia"],
  ["Eswatini", ["Swaziland"]],
  ["Ethiopia"],
  ["Falkland Islands", ["Falkland Islands (the) [Malvinas]"]],
  ["Faroe Islands"],
  ["Fiji"],
  ["Finland"],
  ["France"],
  ["French Guiana"],
  ["French Polynesia"],
  ["French Southern Territories"],
  ["Gabon"],
  ["Gambia"],
  ["Georgia"],
  ["Germany", ["Deutschland"]],
  ["Ghana"],
  ["Gibraltar"],
  ["Greece"],
  ["Greenland"],
  ["Grenada"],
  ["Guadeloupe"],
  ["Guam"],
  ["Guatemala"],
  ["Guernsey"],
  ["Guinea"],
  ["Guinea-Bissau"],
  ["Guyana"],
  ["Haiti"],
  ["Heard and McDonald Islands", ["Heard Island and McDonald Islands"]],
  ["Honduras"],
  ["Hong Kong"],
  ["Hungary"],
  ["Iceland"],
  ["India"],
  ["Indonesia"],
  ["Iran", ["Iran (Islamic Republic of)","Persia"]],
  ["Iraq"],
  ["Ireland"],
  ["Isle of Man"],
  ["Israel"],
  ["Italy"],
  ["Jamaica"],
  ["Japan"],
  ["Jersey"],
  ["Jordan"],
  ["Kazakhstan"],
  ["Kenya"],
  ["Kiribati"],
  ["Kosovo"],
  ["Kuwait"],
  ["Kyrgyzstan"],
  ["Laos", ["Lao People's Democratic Republic"]],
  ["Latvia"],
  ["Lebanon"],
  ["Lesotho"],
  ["Liberia"],
  ["Libya"],
  ["Liechtenstein"],
  ["Lithuania"],
  ["Luxembourg"],
  ["Macao"],
  ["Madagascar"],
  ["Malawi"],
  ["Malaysia"],
  ["Maldives"],
  ["Mali"],
  ["Malta"],
  ["Marshall Islands"],
  ["Martinique"],
  ["Mauritania"],
  ["Mauritius"],
  ["Mayotte"],
  ["Mexico"],
  ["Micronesia", ["Micronesia (Federated States of)"]],
  ["Moldova", ["Moldova (the Republic of)"]],
  ["Monaco"],
  ["Mongolia"],
  ["Montenegro"],
  ["Montserrat"],
  ["Morocco"],
  ["Mozambique"],
  ["Myanmar", ["Burma"]],
  ["Namibia"],
  ["Nauru"],
  ["Nepal"],
  ["Netherlands", ["Netherlands (Kingdom of the)","Holland"]],
  ["New Caledonia"],
  ["New Zealand"],
  ["Nicaragua"],
  ["Niger"],
  ["Nigeria"],
  ["Niue"],
  ["Norfolk Island"],
  ["North Korea", ["Korea (the Democratic People's Republic of)","Korea"]],
  ["North Macedonia"],
  ["Northern Mariana Islands"],
  ["Norway"],
  ["Oman"],
  ["Pakistan"],
  ["Palau"],
  ["Palestine", ["Palestine, State of","Gaza","West Bank"]],
  ["Panama"],
  ["Papua New Guinea"],
  ["Paraguay"],
  ["Peru"],
  ["Philippines"],
  ["Pitcairn Islands", ["Pitcairn"]],
  ["Poland"],
  ["Portugal"],
  ["Puerto Rico"],
  ["Qatar"],
  ["Republic of the Congo", ["Congo","Brazzaville"]],
  ["Réunion"],
  ["Romania"],
  ["Russia", ["Russian Federation"]],
  ["Rwanda"],
  ["Saint Barthélemy"],
  ["Saint Helena", ["Saint Helena, Ascension and Tristan da Cunha"]],
  ["Saint Kitts and Nevis"],
  ["Saint Lucia"],
  ["Saint Martin", ["Saint Martin (French part)"]],
  ["Saint Pierre and Miquelon"],
  ["Saint Vincent and the Grenadines"],
  ["Samoa"],
  ["San Marino"],
  ["São Tomé and Príncipe", ["Sao Tome and Principe"]],
  ["Saudi Arabia"],
  ["Senegal"],
  ["Serbia"],
  ["Seychelles"],
  ["Sierra Leone"],
  ["Singapore"],
  ["Sint Maarten", ["Sint Maarten (Dutch part)"]],
  ["Slovakia"],
  ["Slovenia"],
  ["Solomon Islands"],
  ["Somalia"],
  ["South Africa"],
  ["South Georgia and the South Sandwich Islands"],
  ["South Korea", ["Korea (the Republic of)","Korea"]],
  ["South Sudan"],
  ["Spain", ["España"]],
  ["Sri Lanka"],
  ["Sudan"],
  ["Suriname"],
  ["Svalbard and Jan Mayen"],
  ["Sweden"],
  ["Switzerland", ["Schweiz"]],
  ["Syria", ["Syrian Arab Republic"]],
  ["Taiwan", ["Taiwan (Province of China)"]],
  ["Tajikistan"],
  ["Tanzania", ["Tanzania, the United Republic of"]],
  ["Thailand"],
  ["Timor-Leste", ["East Timor"]],
  ["Togo"],
  ["Tokelau"],
  ["Tonga"],
  ["Trinidad and Tobago"],
  ["Tunisia"],
  ["Türkiye", ["Turkey"]],
  ["Turkmenistan"],
  ["Turks and Caicos Islands"],
  ["Tuvalu"],
  ["U.S. Outlying Islands", ["United States Minor Outlying Islands"]],
  ["U.S. Virgin Islands", ["Virgin Islands (U.S.)"]],
  ["Uganda"],
  ["Ukraine"],
  ["United Arab Emirates", ["UAE","Emirates"]],
  ["United Kingdom", ["United Kingdom of Great Britain and Northern Ireland","UK","Great Britain","Britain","England","Scotland","Wales","Northern Ireland"]],
  ["United States", ["United States of America","USA","US","America"]],
  ["Uruguay"],
  ["Uzbekistan"],
  ["Vanuatu"],
  ["Vatican City", ["Holy See"]],
  ["Venezuela", ["Venezuela (Bolivarian Republic of)"]],
  ["Vietnam", ["Viet Nam"]],
  ["Wallis and Futuna"],
  ["Western Sahara", ["Western Sahara*"]],
  ["Yemen"],
  ["Zambia"],
  ["Zimbabwe"],
];
